In [1]:
import numpy as np

In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.full((4,6), 8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.arange(0, 1000, 10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510,
       520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640,
       650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770,
       780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900,
       910, 920, 930, 940, 950, 960, 970, 980, 990])

In [21]:
np.linspace(1, 50, 5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [29]:
myarr = np.array([[10, 20 ,30], [40, 50, 60]])

In [30]:
myarr

array([[10, 20, 30],
       [40, 50, 60]])

In [31]:
print("Shape: ", myarr.shape)
print("Size: ", myarr.size) 
print("Dimensions: ", myarr.ndim)
print("Data type: ", myarr.dtype)

Shape:  (2, 3)
Size:  6
Dimensions:  2
Data type:  int64


In [38]:
myarr = np.array([[10, 20 ,30], [40, 50, 60]], dtype = np.float32)

print(myarr.dtype)

float32


In [42]:
n = myarr.astype('float64')

In [43]:
n

array([[10., 20., 30.],
       [40., 50., 60.]])

In [44]:
n.dtype

dtype('float64')

In [45]:
myarr.dtype

dtype('float32')

In [46]:
myarr = np.array([[10, 20 ,30], [40, 50, 60]])

In [47]:
myarr.shape

(2, 3)

In [48]:
changed = myarr.reshape((3, 2))

In [49]:
changed

array([[10, 20],
       [30, 40],
       [50, 60]])

In [50]:
myarr

array([[10, 20, 30],
       [40, 50, 60]])

In [53]:
myarr.flatten()

array([10, 20, 30, 40, 50, 60])