In [1]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
flat = arr.flatten()

In [8]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
flat[0]

np.int64(1)

In [11]:
flat[3:6]

array([4, 5, 6])

In [12]:
flat[:5]

array([1, 2, 3, 4, 5])

In [13]:
flat[5:]

array([ 6,  7,  8,  9, 10, 11, 12])

In [14]:
flat[::4]

array([1, 5, 9])

In [15]:
b = flat[3:7]

In [16]:
b

array([4, 5, 6, 7])

In [17]:
b[0] = 22222

In [18]:
b

array([22222,     5,     6,     7])

In [19]:
flat

array([    1,     2,     3, 22222,     5,     6,     7,     8,     9,
          10,    11,    12])

In [20]:
c = flat[4:8]

In [21]:
c

array([5, 6, 7, 8])

In [22]:
arr = np.array([1, 34, 56, 3, 78, 90, 100])

In [23]:
arr[[0, 4, 6]]

array([  1,  78, 100])

In [26]:
arr [arr < 78]

array([ 1, 34, 56,  3])