In [6]:
import numpy as np

In [8]:
kri = np.array([[1,5,9],[4,8,7],[6,5,7]])

In [9]:
kri

array([[1, 5, 9],
       [4, 8, 7],
       [6, 5, 7]])

In [10]:
kri.shape

(3, 3)

In [11]:
ada = np.array([1.1,2.2,3.3])

In [12]:
ada

array([1.1, 2.2, 3.3])

In [13]:
x = ada.astype("int")

In [16]:
x

array([1, 2, 3])

In [30]:
fn = np.array([1,2,3,4,5,6])

In [33]:
fn

array([1, 2, 3, 4, 5, 6])

In [34]:
fn[[1,3,5]]

array([2, 4, 6])

In [39]:
reshaped = kri.reshape(9,1)

In [40]:
reshaped

array([[1],
       [5],
       [9],
       [4],
       [8],
       [7],
       [6],
       [5],
       [7]])

In [41]:
bool = np.array([81,55,45,51,1,2,3,4,5,6])
bool

array([81, 55, 45, 51,  1,  2,  3,  4,  5,  6])

In [43]:
bool[bool>50]

array([81, 55, 51])