In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
 arr[0]

array([1, 2, 3])

In [10]:
np.sum(arr, axis = 0) # column-wise sum

array([12, 15, 18])

In [9]:
np.sum(arr, axis = 1) # row-wise sum

array([ 6, 15, 24])

In [11]:
arr [0][2]

np.int64(3)

In [14]:
arr[2, 2]

np.int64(9)

In [24]:
arr[1:3, 0:2]

array([[4, 5],
       [7, 8]])

In [27]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [10, 11, 12]]])

In [33]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
arr3D[:, 0, :] = 5

In [43]:
arr3D

array([[[ 5,  5,  5],
        [ 4,  5,  6]],

       [[ 5,  5,  5],
        [10, 11, 12]]])