In [14]:
import numpy as np

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr = arr**2
arr

array([ 1,  4,  9, 16, 25, 36])

In [17]:
arr + 10

array([11, 14, 19, 26, 35, 46])

In [20]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
result = arr1 + arr2
result

array([[2, 4, 6],
       [5, 7, 9]])

In [21]:
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

In [23]:
mean = data.mean(axis=0)
std = data.std(axis=0)

normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
