In [1]:
import numpy as np

In [2]:
arr = np.array([2, 56, 5, 7, 45])

In [3]:
np.mean(arr)

np.float64(23.0)

In [4]:
np.std(arr)

np.float64(22.777181564012697)

In [5]:
np.var(arr)

np.float64(518.8)

In [6]:
np.min(arr)

np.int64(2)

In [7]:
np.max(arr)

np.int64(56)

In [8]:
np.sum(arr)

np.int64(115)

In [9]:
np.prod(arr)

np.int64(176400)

In [10]:
np.median(arr)

np.float64(7.0)

In [12]:
np.argmin(arr)

np.int64(0)

In [13]:
np.argmax(arr)

np.int64(1)

In [14]:
np.corrcoef(arr)

np.float64(1.0)

In [15]:
np.unique(arr)

array([ 2,  5,  7, 45, 56])

In [16]:
np.diff(arr)

array([ 54, -51,   2,  38])

In [17]:
np.cumsum(arr)

array([  2,  58,  63,  70, 115])

In [19]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.log(arr)

array([0.69314718, 4.02535169, 1.60943791, 1.94591015, 3.80666249])

In [23]:
np.exp(arr)

array([7.38905610e+00, 2.09165950e+24, 1.48413159e+02, 1.09663316e+03,
       3.49342711e+19])

In [25]:
np.percentile(arr,50)

np.float64(7.0)